import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { Open_Sans } from "next/font/google";
import UnityBridge from "@/components/unity/Bridge";
import ClaimTokenMount from "@/components/Home/ClaimToken";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],        // 400 = normal, 700 = bold
  style: ["normal", "italic"],   // enable italic
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.className} antialiased` }
      >
       <Providers><UnityBridge /> {children} </Providers>
      </body>
    </html>
  );
}
